spring.application.name=SaludConecta
server.port=8080

spring.datasource.url=jdbc:sqlite:saludconecta.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.profiles.active=datafaker

spring.flyway.enabled=true
spring.sql.init.mode=never
