server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: saludconecta
              uri: http://localhost:8080
              predicates:
                - Path=/api/pacientes/**,/api/medicos/**,/api/tratamientos/**,/api/test-conexion/**

            - id: microservicio-usuarios
              uri: http://localhost:8081
              predicates:
                - Path=/api/usuarios/**,/api/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: API Gateway SaludConecta
    description: Punto de entrada para SaludConecta y microservicio-usuarios
